services:
  mongo:
    image: mongo:7
    container_name: creativ_pressing_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: pressing
    ports:
      - "27017:27017"
    volumes:
      - creativ_pressing_mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  creativ_pressing_mongodata:
