services:
  - type: web
    name: creativ-pressing-api
    env: docker
    plan: free
    healthCheckPath: /api/shops
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://creativ-pressing.vercel.app,http://localhost:5173,http://localhost:3000
      - key: DATABASE_URL
        fromDatabase:
          name: creativ-pressing-db
          property: connectionString

databases:
  - name: creativ-pressing-db
    plan: free
